version: '3.9'

services:
  db:
    image: postgres:16
    container_name: adm-db
    restart: always
    environment:
      POSTGRES_DB: adm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - adm_pgdata:/var/lib/postgresql/data
    networks:
      - adm-net

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: adm-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      TZ: America/Sao_Paulo
    ports:
      - "15432:80"
    depends_on:
      - db
    networks:
      - adm-net

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: adm-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"     # Porta padrão de comunicação
      - "15672:15672"   # Painel de controle Web do RabbitMQ
    networks:
      - adm-net

networks:
  adm-net:

volumes:
  adm_pgdata: