spring:
  application:
    name: adm

  datasource:
    url: jdbc:postgresql://localhost:5432/adm
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update        # use "update" se quiser gerar tabelas automaticamente
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: America/Sao_Paulo

  sql:
    init:
      mode: never           # use "always" se quiser rodar scripts data.sql/schema.sql

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    function:
      definition: consumer
    stream:
      bindings:
        ticketProducer-out-0:
          destination: ticket
          content-type: application/json
#          producer:
#            required-groups: demo-group
        final-dlq-ticket-out-0:
          destination: final.dlq.ticket.created
          content-type: application/json
          producer:
            required-groups: final-dlq-a
        consumer-in-0:
          destination: ticket
          group: demo-group
          consumer:
            max-attempts: 1
            bind-queue: false
            declare-exchange: false
            queue-name-group-only: true
      rabbit:
        bindings:
          consumer-in-0:
            consumer:
              auto-bind-dlq: true
              dlq-ttl: 10000
              dlq-dead-letter-exchange:

server:
  port: 8081
  servlet:
    context-path: /